app:
  base-url: ${APP_BASE_URL:http://192.168.15.7:8090/}

spring:
  application:
    name: schedule

  datasource:
    url: jdbc:postgresql://localhost:8091/schedule
    username: schedule
    password: schedule
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    clear-checksums: true
    change-log: classpath:db/changelog/db.changelog-master-public.xml
    default-schema: public
    contexts: local

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8090

jwt:
  secret: ${JWT_SCRET_KEY:CHAVE-JWT-COM-MAIS-DE-256-BIT-123456789}
  expirationMs: 14400000

front-url: ${FRONT_URL:http://localhost:3000}
